services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: athvexa
      POSTGRES_PASSWORD: athvexa
      POSTGRES_DB: athvexa
    ports:
      - "5432:5432"
    volumes:
      - athvexa_pg:/var/lib/postgresql/data

volumes:
  athvexa_pg:
